config/routes.rb
WeddingApp::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/contact"
  get "static_pages/venue"
  get "static_pages/accommodation" 

  root :to => 'static_pages#home'

  match '/contact', to:'static_pages#contact'
  match '/venue', to:'static_pages#venue'   
  match '/accommodation', to:'static_pages#accommodation'       

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def venue
  end

  def accommodation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Rachael and Jay Wedding | <%= yield(:title) %> </title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->	  
	</head>
	<body>
		<header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
        <!-- <%= link_to "Rachael and Jay", '#', id: "logo" %> -->
          <nav>
            <ul class="nav pull-right">
            	<li><%= link_to "Home", root_path  %></li>
              <li><%= link_to "Venue", venue_path %></li>
              <li><%= link_to "Accomodation", accommodation_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>	
    <div class="left hero-unit">	
		<%= yield %>
		</div>
	</body>
</html>

app/views/static_pages/accommodation.html.erb
<% provide(:title, 'Accommodation') %>

<h1> Accommodation </h1>
<p>
	Information wedding is a wedding, and we would like
	you to come and have fun.  Dancing and fun and eating.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1> Contact </h1>
<p>
	
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<h1> Rachael and Jay's Wedding </h1>
<p>

</p>

app/views/static_pages/venue.html.erb
<% provide(:title, 'Venue') %>

<h1> Venue </h1>
<p>
	Information wedding is a wedding, and we would like
	you to come and have fun.  Dancing and fun and eating.
</p>